[package]
name = "auth_middleware"
version = "0.1.0"
edition = "2024"

[dependencies]
hmac = "0.12.1"
sha2 = "0.10.9"
base64 = "0.22.1"
chrono = "0.4"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
anyhow = "1.0.98"
spin-sdk = "3.1.0"